import { getMoodIcon } from "./moodIcons";

export const mood = {
  unselected: {
    subemotions: "Unselected Mood",
    spaceObject: "Unknown Planet",
    colorHex: "#6A7282",
    colorName: "slate-200",
    textColor: "text-slate-200",
    borderColor: "border-slate-200",
    icon: getMoodIcon("unselected"),
  },
  joy: {
    subemotions: "Happiness, Hope, Excitement",
    spaceObject: "Shooting Star",
    colorHex: "#FFD230",
    colorName: "amber-300",
    textColor: "text-amber-300",
    borderColor: "border-amber-300",
    icon: getMoodIcon("joy"),
  },
  gratitude: {
    subemotions: "Thankfulness, Appreciation, Nostalgia",
    spaceObject: "Glowing Star",
    colorHex: "#FF8904",
    colorName: "orange-400",
    textColor: "text-orange-400",
    borderColor: "border-orange-400",
    icon: getMoodIcon("gratitude"),
  },
  growth: {
    subemotions: "Change, Restarting, Evolving",
    spaceObject: "Catalyst Rocket",
    colorHex: "#5EE9B5",
    colorName: "emerald-300",
    textColor: "text-emerald-300",
    borderColor: "border-emerald-300",
    icon: getMoodIcon("growth"),
  },
  connection: {
    subemotions: "Belonging, Empathy, Love",
    spaceObject: "Twin Stars",
    colorHex: "#FB64B6",
    colorName: "pink-400",
    textColor: "text-pink-400",
    borderColor: "border-pink-400",
    icon: getMoodIcon("connection"),
  },
  stillness: {
    subemotions: "Peace, Calm, Serenity",
    spaceObject: "Crystal Moon",
    colorHex: "#A2F4FD",
    colorName: "cyan-300",
    textColor: "text-cyan-200",
    borderColor: "border-cyan-200",
    icon: getMoodIcon("stillness"),
  },
  wonder: {
    subemotions: "Curiosity, Awe, Amazement",
    spaceObject: "Nebula Bloom",
    colorHex: "#A684FF",
    colorName: "violet-400",
    textColor: "text-violet-400",
    borderColor: "border-violet-400",
    icon: getMoodIcon("wonder"),
  },
  anger: {
    subemotions: "Frustration, Rage, Irritation",
    spaceObject: "Meteor Storm",
    colorHex: "#FB2C36",
    colorName: "red-500",
    textColor: "text-red-500",
    borderColor: "border-red-500",
    icon: getMoodIcon("anger"),
  },
  turbulence: {
    subemotions: "Anxiety, Shame, Confusion",
    spaceObject: "Solar Flare",
    colorHex: "#FF6900",
    colorName: "orange-600",
    textColor: "text-orange-600",
    borderColor: "border-orange-600",
    icon: getMoodIcon("turbulence"),
  },
  sadness: {
    subemotions: "Shame, Disappointment, Melancholy",
    spaceObject: "Frozen Planet",
    colorHex: "#0069A8",
    colorName: "sky-500",
    textColor: "text-sky-500",
    borderColor: "border-sky-500",
    icon: getMoodIcon("sadness"),
  },
  grief: {
    subemotions: "Emptiness, Loss, Despair",
    spaceObject: "Black Hole",
    colorHex: "#0B4F4A",
    colorName: "grief-500",
    textColor: "text-grief-500",
    borderColor: "border-grief-500",
    icon: getMoodIcon("grief"),
  },
  lost: {
    subemotions: "Lonely, Stuck, Directionless",
    spaceObject: "Lost Satellite",
    colorHex: "#99A1AF",
    colorName: "gray-400",
    textColor: "text-gray-400",
    borderColor: "border-gray-400",
    icon: getMoodIcon("lost"),
  },
};
